"""phase2_core_ops

Revision ID: 002e08600364
Revises: 0011
Create Date: 2026-08-10 00:51:58.260889

"""
from alembic import op
import sqlalchemy as sa


revision = '002e08600364'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insiden',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('jenis_insiden', sa.Enum('pemadaman', 'penyelamatan', name='jenisinsiden'), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('objek', sa.String(length=200), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('pelapor_nama', sa.String(length=100), nullable=False),
    sa.Column('pelapor_kontak', sa.String(length=50), nullable=False),
    sa.Column('waktu_lapor', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('waktu_berangkat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waktu_tiba', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waktu_selesai', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('menunggu', 'berangkat', 'penanganan', 'selesai', 'batal', name='statusinsiden'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insiden_tenant_id'), 'insiden', ['tenant_id'], unique=False)
    op.create_table('inspeksi_proteksi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('objek_inspeksi', sa.String(length=200), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('tanggal_inspeksi', sa.Date(), nullable=False),
    sa.Column('status_kepatuhan', sa.Enum('patuh', 'sebagian', 'tidak_patuh', name='statuskepatuhan'), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('inspektur_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inspektur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspeksi_proteksi_tenant_id'), 'inspeksi_proteksi', ['tenant_id'], unique=False)
    op.create_table('insiden_armada',
    sa.Column('insiden_id', sa.UUID(), nullable=False),
    sa.Column('armada_id', sa.BigInteger(), nullable=False),
    sa.Column('waktu_dispatch', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['armada_id'], ['armada.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insiden_id'], ['insiden.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insiden_id', 'armada_id')
    )
    op.create_table('inventaris',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nama_barang', sa.String(length=200), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('kondisi', sa.Enum('baik', 'rusak_ringan', 'rusak_berat', name='kondisibarang'), nullable=False),
    sa.Column('lokasi_id', sa.Integer(), nullable=True),
    sa.Column('armada_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['armada_id'], ['armada.id'], ),
    sa.ForeignKeyConstraint(['lokasi_id'], ['lokasi.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventaris_tenant_id'), 'inventaris', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventaris_tenant_id'), table_name='inventaris')
    op.drop_table('inventaris')
    op.drop_table('insiden_armada')
    op.drop_index(op.f('ix_inspeksi_proteksi_tenant_id'), table_name='inspeksi_proteksi')
    op.drop_table('inspeksi_proteksi')
    op.drop_index(op.f('ix_insiden_tenant_id'), table_name='insiden')
    op.drop_table('insiden')
    # ### end Alembic commands ###
