"""add sarpras and stations

Revision ID: 01e927c7b9cd
Revises: 2fcd1a395c9c
Create Date: 2026-08-10 22:41:03.467715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '01e927c7b9cd'
down_revision = '2fcd1a395c9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('alamat', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('kapasitas_personil', sa.Integer(), nullable=True),
    sa.Column('is_bahari_post', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_tenant_id'), 'stations', ['tenant_id'], unique=False)
    
    tipe_barang_enum = postgresql.ENUM('equipment', 'asset', 'consumable', name='tipebarang')
    tipe_barang_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('inventaris', sa.Column('tipe_barang', tipe_barang_enum, server_default='equipment', nullable=False))
    
    op.add_column('inventaris', sa.Column('metadata_tambahan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventaris', 'metadata_tambahan')
    op.drop_column('inventaris', 'tipe_barang')
    
    tipe_barang_enum = postgresql.ENUM('equipment', 'asset', 'consumable', name='tipebarang')
    tipe_barang_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_stations_tenant_id'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
