"""Add settings skpd fields

Revision ID: 127714e56177
Revises: 01e927c7b9cd
Create Date: 2026-08-11 13:11:42.231481

"""
from alembic import op
import sqlalchemy as sa


revision = '127714e56177'
down_revision = '01e927c7b9cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('personnel_count', sa.Integer(), nullable=True))
    op.add_column('app_settings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('app_settings', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('tenant_settings', sa.Column('personnel_count', sa.Integer(), nullable=True))
    op.add_column('tenant_settings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tenant_settings', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'longitude')
    op.drop_column('tenant_settings', 'latitude')
    op.drop_column('tenant_settings', 'personnel_count')
    op.drop_column('app_settings', 'longitude')
    op.drop_column('app_settings', 'latitude')
    op.drop_column('app_settings', 'personnel_count')
    # ### end Alembic commands ###
