"""add lat lng to lokasi

Revision ID: 14feaef2c083
Revises: 310143c039c8
Create Date: 2026-08-18 11:18:03.231301

"""
from alembic import op
import sqlalchemy as sa


revision = '14feaef2c083'
down_revision = '310143c039c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lokasi', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('lokasi', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lokasi', 'longitude')
    op.drop_column('lokasi', 'latitude')
    # ### end Alembic commands ###
