"""Add UnitOrganisasi and Personil

Revision ID: 1b78a6478c09
Revises: b862e0469861
Create Date: 2026-08-19 05:47:59.263263

"""
from alembic import op
import sqlalchemy as sa


revision = '1b78a6478c09'
down_revision = 'b862e0469861'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kompi',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kompi_id'), 'kompi', ['id'], unique=False)
    op.create_index(op.f('ix_kompi_tenant_id'), 'kompi', ['tenant_id'], unique=False)
    op.create_table('pleton',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kompi_id', sa.BigInteger(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['kompi_id'], ['kompi.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pleton_id'), 'pleton', ['id'], unique=False)
    op.create_index(op.f('ix_pleton_tenant_id'), 'pleton', ['tenant_id'], unique=False)
    op.create_table('regu',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pleton_id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pleton_id'], ['pleton.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regu_id'), 'regu', ['id'], unique=False)
    op.create_index(op.f('ix_regu_tenant_id'), 'regu', ['tenant_id'], unique=False)
    op.create_table('personil',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nip_nik', sa.String(length=50), nullable=False),
    sa.Column('jabatan', sa.Enum('danki', 'danton', 'danru', 'operator', 'lainnya', name='jabatan_personil'), nullable=False),
    sa.Column('regu_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['regu_id'], ['regu.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_personil_id'), 'personil', ['id'], unique=False)
    op.create_index(op.f('ix_personil_nip_nik'), 'personil', ['nip_nik'], unique=True)
    op.create_index(op.f('ix_personil_tenant_id'), 'personil', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=150), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_personil_tenant_id'), table_name='personil')
    op.drop_index(op.f('ix_personil_nip_nik'), table_name='personil')
    op.drop_index(op.f('ix_personil_id'), table_name='personil')
    op.drop_table('personil')
    op.drop_index(op.f('ix_regu_tenant_id'), table_name='regu')
    op.drop_index(op.f('ix_regu_id'), table_name='regu')
    op.drop_table('regu')
    op.drop_index(op.f('ix_pleton_tenant_id'), table_name='pleton')
    op.drop_index(op.f('ix_pleton_id'), table_name='pleton')
    op.drop_table('pleton')
    op.drop_index(op.f('ix_kompi_tenant_id'), table_name='kompi')
    op.drop_index(op.f('ix_kompi_id'), table_name='kompi')
    op.drop_table('kompi')
    # ### end Alembic commands ###
