"""create_edukasi_table

Revision ID: 2057c98ccde4
Revises: 8edbd2c5b3d4
Create Date: 2026-08-10 13:41:24.886616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '2057c98ccde4'
down_revision = '8edbd2c5b3d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edukasi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kategori', sa.Enum('sosialisasi_masyarakat', 'kunjungan_sekolah', 'pelatihan', 'lainnya', name='edukasikategori'), nullable=False),
    sa.Column('judul_kegiatan', sa.String(length=255), nullable=False),
    sa.Column('tanggal_pelaksanaan', sa.DateTime(), nullable=False),
    sa.Column('lokasi', sa.String(length=255), nullable=False),
    sa.Column('target_audiens', sa.String(length=255), nullable=True),
    sa.Column('jumlah_peserta', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'ongoing', 'completed', 'cancelled', name='edukasistatus'), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('dokumentasi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edukasi')
    # ### end Alembic commands ###
