"""add_driver_id_to_armada

Revision ID: 27fb79c5cd16
Revises: d9618a7a842f
Create Date: 2026-08-27 03:42:11.066461

"""
from alembic import op
import sqlalchemy as sa


revision = '27fb79c5cd16'
down_revision = 'd9618a7a842f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armada', sa.Column('driver_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'armada', 'users', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'armada', type_='foreignkey')
    op.drop_column('armada', 'driver_id')
    # ### end Alembic commands ###
