"""Create AsetBahari table

Revision ID: 2fcd1a395c9c
Revises: 8d3fafae757c
Create Date: 2026-08-10 11:09:10.129856

"""
from alembic import op
import sqlalchemy as sa


revision = '2fcd1a395c9c'
down_revision = '8d3fafae757c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aset_bahari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipe', sa.Enum('fire_boat', 'fire_pump', 'posko', 'pulau', name='tipeasetbahari'), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('kapasitas', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ready', 'maintenance', 'deployed', name='statusasetbahari'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aset_bahari')
    # ### end Alembic commands ###
