"""add_whatsapp_gateway_settings

Revision ID: 310143c039c8
Revises: 240d4ff313e1
Create Date: 2026-08-16 07:57:06.731483

"""
from alembic import op
import sqlalchemy as sa


revision = '310143c039c8'
down_revision = '240d4ff313e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('wa_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('app_settings', sa.Column('wa_provider', sa.String(length=50), server_default='fonnte', nullable=False))
    op.add_column('app_settings', sa.Column('wa_api_token', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('wa_api_url', sa.String(length=255), server_default='https://api.fonnte.com/send', nullable=True))
    op.add_column('app_settings', sa.Column('wa_siaga_target', sa.Text(), nullable=True))
    op.add_column('app_settings', sa.Column('wa_instance_name', sa.String(length=100), server_default='sim-armada', nullable=True))

    op.add_column('tenant_settings', sa.Column('wa_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('tenant_settings', sa.Column('wa_provider', sa.String(length=50), server_default='fonnte', nullable=False))
    op.add_column('tenant_settings', sa.Column('wa_api_token', sa.String(length=255), nullable=True))
    op.add_column('tenant_settings', sa.Column('wa_api_url', sa.String(length=255), server_default='https://api.fonnte.com/send', nullable=True))
    op.add_column('tenant_settings', sa.Column('wa_siaga_target', sa.Text(), nullable=True))
    op.add_column('tenant_settings', sa.Column('wa_instance_name', sa.String(length=100), server_default='sim-armada', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'wa_instance_name')
    op.drop_column('tenant_settings', 'wa_siaga_target')
    op.drop_column('tenant_settings', 'wa_api_url')
    op.drop_column('tenant_settings', 'wa_api_token')
    op.drop_column('tenant_settings', 'wa_provider')
    op.drop_column('tenant_settings', 'wa_enabled')
    op.drop_column('app_settings', 'wa_instance_name')
    op.drop_column('app_settings', 'wa_siaga_target')
    op.drop_column('app_settings', 'wa_api_url')
    op.drop_column('app_settings', 'wa_api_token')
    op.drop_column('app_settings', 'wa_provider')
    op.drop_column('app_settings', 'wa_enabled')
    # ### end Alembic commands ###
