"""Add dashboard media fields to tenant_settings

Revision ID: 37b634d90af8
Revises: 8ad13a99a05f
Create Date: 2026-08-13 18:58:39.036683

"""
from alembic import op
import sqlalchemy as sa


revision = '37b634d90af8'
down_revision = '8ad13a99a05f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_settings', sa.Column('dashboard_video_url', sa.String(length=500), nullable=True))
    op.add_column('tenant_settings', sa.Column('dashboard_image_url', sa.String(length=500), nullable=True))
    op.add_column('tenant_settings', sa.Column('dashboard_running_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'dashboard_running_text')
    op.drop_column('tenant_settings', 'dashboard_image_url')
    op.drop_column('tenant_settings', 'dashboard_video_url')
    # ### end Alembic commands ###
