"""Restore role column in users for legacy support

Revision ID: 3f245a373a76
Revises: b9adb34cb589
Create Date: 2026-08-10 01:40:17.266355

"""
from alembic import op
import sqlalchemy as sa


revision = '3f245a373a76'
down_revision = 'b9adb34cb589'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('administrator', 'pimpinan', 'kabid', 'operator', 'teknisi', name='user_role'), nullable=False, server_default='operator'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
