"""Add pelapor_alamat and jumlah_terdampak to insiden

Revision ID: 42030a7359fd
Revises: 127714e56177
Create Date: 2026-08-11 20:19:34.042704

"""
from alembic import op
import sqlalchemy as sa


revision = '42030a7359fd'
down_revision = '127714e56177'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insiden', sa.Column('pelapor_alamat', sa.Text(), nullable=True))
    op.add_column('insiden', sa.Column('jumlah_terdampak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insiden', 'jumlah_terdampak')
    op.drop_column('insiden', 'pelapor_alamat')
    # ### end Alembic commands ###
