"""add personnel_tracking table

Revision ID: 45229defad86
Revises: 14feaef2c083
Create Date: 2026-08-18 20:11:01.745249

"""
from alembic import op
import sqlalchemy as sa


revision = '45229defad86'
down_revision = '14feaef2c083'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel_tracking',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('battery_pct', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_tracking_id'), 'personnel_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_personnel_tracking_tenant_id'), 'personnel_tracking', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_personnel_tracking_user_id'), 'personnel_tracking', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personnel_tracking_user_id'), table_name='personnel_tracking')
    op.drop_index(op.f('ix_personnel_tracking_tenant_id'), table_name='personnel_tracking')
    op.drop_index(op.f('ix_personnel_tracking_id'), table_name='personnel_tracking')
    op.drop_table('personnel_tracking')
    # ### end Alembic commands ###
