"""remove kabid role

Revision ID: 5842594a1c6a
Revises: f1a2b3c4d5e6
Create Date: 2026-08-14 15:53:48.400920

"""
from alembic import op
import sqlalchemy as sa


revision = '5842594a1c6a'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("UPDATE users SET role = 'pimpinan' WHERE role = 'kabid'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
