"""Add latitude, longitude and override waktu_lapor

Revision ID: 69d59b3a6127
Revises: 3f245a373a76
Create Date: 2026-08-09 19:12:22.740053

"""
from alembic import op
import sqlalchemy as sa


revision = '69d59b3a6127'
down_revision = '3f245a373a76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insiden', sa.Column('latitude', sa.String(length=50), nullable=True))
    op.add_column('insiden', sa.Column('longitude', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insiden', 'longitude')
    op.drop_column('insiden', 'latitude')
    # ### end Alembic commands ###
