"""Add bahari models

Revision ID: 6eb71985dfee
Revises: a551065abf48
Create Date: 2026-08-12 00:26:47.462341

"""
from alembic import op
import sqlalchemy as sa


revision = '6eb71985dfee'
down_revision = 'a551065abf48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insiden_bahari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('lokasi', sa.String(), nullable=False),
    sa.Column('skala', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('jumlah_korban', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insiden_bahari_tenant_id'), 'insiden_bahari', ['tenant_id'], unique=False)
    op.create_table('komunitas_bahari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('lokasi', sa.String(), nullable=False),
    sa.Column('jumlah_anggota', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('kontak_utama', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_komunitas_bahari_tenant_id'), 'komunitas_bahari', ['tenant_id'], unique=False)
    op.create_table('pelatihan_bahari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kapasitas', sa.Integer(), nullable=False),
    sa.Column('peserta_terdaftar', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lokasi', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pelatihan_bahari_tenant_id'), 'pelatihan_bahari', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pelatihan_bahari_tenant_id'), table_name='pelatihan_bahari')
    op.drop_table('pelatihan_bahari')
    op.drop_index(op.f('ix_komunitas_bahari_tenant_id'), table_name='komunitas_bahari')
    op.drop_table('komunitas_bahari')
    op.drop_index(op.f('ix_insiden_bahari_tenant_id'), table_name='insiden_bahari')
    op.drop_table('insiden_bahari')
    # ### end Alembic commands ###
