"""add_post_handling_fields

Revision ID: 88aab93ffc53
Revises: c86befb24e5d
Create Date: 2026-08-13 22:50:05.011438

"""
from alembic import op
import sqlalchemy as sa


revision = '88aab93ffc53'
down_revision = 'c86befb24e5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insiden', sa.Column('luas_areal', sa.Integer(), nullable=True))
    op.add_column('insiden', sa.Column('korban_meninggal', sa.Integer(), nullable=True))
    op.add_column('insiden', sa.Column('korban_luka', sa.Integer(), nullable=True))
    op.add_column('insiden', sa.Column('korban_kk', sa.Integer(), nullable=True))
    op.add_column('insiden', sa.Column('taksiran_kerugian', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insiden', 'taksiran_kerugian')
    op.drop_column('insiden', 'korban_kk')
    op.drop_column('insiden', 'korban_luka')
    op.drop_column('insiden', 'korban_meninggal')
    op.drop_column('insiden', 'luas_areal')
    # ### end Alembic commands ###
