"""Add dashboard settings fields

Revision ID: 8ad13a99a05f
Revises: 6eb71985dfee
Create Date: 2026-08-13 04:58:32.836547

"""
from alembic import op
import sqlalchemy as sa


revision = '8ad13a99a05f'
down_revision = '6eb71985dfee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('dashboard_video_url', sa.String(length=500), nullable=True))
    op.add_column('app_settings', sa.Column('dashboard_image_url', sa.String(length=500), nullable=True))
    op.add_column('app_settings', sa.Column('dashboard_running_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'dashboard_running_text')
    op.drop_column('app_settings', 'dashboard_image_url')
    op.drop_column('app_settings', 'dashboard_video_url')
    # ### end Alembic commands ###
