"""create_relawan_table

Revision ID: 8d3fafae757c
Revises: 2057c98ccde4
Create Date: 2026-08-10 13:47:27.448148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8d3fafae757c'
down_revision = '2057c98ccde4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relawan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('komunitas', sa.String(length=255), nullable=True),
    sa.Column('biodata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trainings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('incident_participation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'in_mission', name='statusrelawan'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relawan')
    # ### end Alembic commands ###
