"""Pencegahan (Inspection) rich data

Revision ID: 8edbd2c5b3d4
Revises: 69d59b3a6127
Create Date: 2026-08-10 13:29:23.118396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8edbd2c5b3d4'
down_revision = '69d59b3a6127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE status_inspeksi_enum AS ENUM ('pending', 'ongoing', 'completed', 'followed_up');")
    op.execute("CREATE TYPE status_approval_enum AS ENUM ('pending', 'approved', 'rejected');")
    op.execute("CREATE TYPE status_kepatuhan_enum AS ENUM ('patuh', 'sebagian', 'tidak_patuh');")
    
    op.add_column('inspeksi_proteksi', sa.Column('building_name', sa.String(length=200), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('owner_name', sa.String(length=200), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('latitude', sa.String(length=50), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('longitude', sa.String(length=50), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('status', postgresql.ENUM('pending', 'ongoing', 'completed', 'followed_up', name='status_inspeksi_enum', create_type=False), nullable=True))
    
    # Set default value then make non nullable
    op.execute("UPDATE inspeksi_proteksi SET status = 'pending'")
    op.alter_column('inspeksi_proteksi', 'status', nullable=False)
    
    op.add_column('inspeksi_proteksi', sa.Column('recommendations', sa.Text(), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('approval_status', postgresql.ENUM('pending', 'approved', 'rejected', name='status_approval_enum', create_type=False), nullable=True))
    
    op.execute("UPDATE inspeksi_proteksi SET approval_status = 'pending'")
    op.alter_column('inspeksi_proteksi', 'approval_status', nullable=False)
    op.add_column('inspeksi_proteksi', sa.Column('approved_by_id', sa.BigInteger(), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspeksi_proteksi', sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('inspeksi_proteksi', 'status_kepatuhan',
               existing_type=postgresql.ENUM('patuh', 'sebagian', 'tidak_patuh', name='statuskepatuhan'),
               type_=sa.Enum('patuh', 'sebagian', 'tidak_patuh', name='status_kepatuhan_enum'),
               existing_nullable=False,
               postgresql_using='status_kepatuhan::text::status_kepatuhan_enum')
    op.create_foreign_key(None, 'inspeksi_proteksi', 'users', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspeksi_proteksi', type_='foreignkey')
    op.alter_column('inspeksi_proteksi', 'status_kepatuhan',
               existing_type=sa.Enum('patuh', 'sebagian', 'tidak_patuh', name='status_kepatuhan_enum'),
               type_=postgresql.ENUM('patuh', 'sebagian', 'tidak_patuh', name='statuskepatuhan'),
               existing_nullable=False)
    op.drop_column('inspeksi_proteksi', 'documents')
    op.drop_column('inspeksi_proteksi', 'photos')
    op.drop_column('inspeksi_proteksi', 'findings')
    op.drop_column('inspeksi_proteksi', 'checklist')
    op.drop_column('inspeksi_proteksi', 'approved_by_id')
    op.drop_column('inspeksi_proteksi', 'approval_status')
    op.drop_column('inspeksi_proteksi', 'recommendations')
    op.drop_column('inspeksi_proteksi', 'status')
    op.drop_column('inspeksi_proteksi', 'longitude')
    op.drop_column('inspeksi_proteksi', 'latitude')
    op.drop_column('inspeksi_proteksi', 'owner_name')
    op.drop_column('inspeksi_proteksi', 'building_name')
    # ### end Alembic commands ###
