"""Add is_verified to Insiden

Revision ID: a551065abf48
Revises: 42030a7359fd
Create Date: 2026-08-11 23:20:13.786893

"""
from alembic import op
import sqlalchemy as sa


revision = 'a551065abf48'
down_revision = '42030a7359fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insiden', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insiden', 'is_verified')
    # ### end Alembic commands ###
