"""Update kompi pleton regu models add deskripsi make kode optional

Revision ID: a7d77b916c14
Revises: 1b78a6478c09
Create Date: 2026-08-19 06:21:43.103862

"""
from alembic import op
import sqlalchemy as sa


revision = 'a7d77b916c14'
down_revision = '1b78a6478c09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kompi', sa.Column('deskripsi', sa.String(), nullable=True))
    op.alter_column('kompi', 'kode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('pleton', sa.Column('deskripsi', sa.String(), nullable=True))
    op.alter_column('pleton', 'kode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('regu', sa.Column('deskripsi', sa.String(), nullable=True))
    op.alter_column('regu', 'kode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regu', 'kode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('regu', 'deskripsi')
    op.alter_column('pleton', 'kode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('pleton', 'deskripsi')
    op.alter_column('kompi', 'kode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('kompi', 'deskripsi')
    # ### end Alembic commands ###
