"""add_personnel_status_to_tracking

Revision ID: b862e0469861
Revises: 45229defad86
Create Date: 2026-08-18 22:32:33.473533

"""
from alembic import op
import sqlalchemy as sa


revision = 'b862e0469861'
down_revision = '45229defad86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
