"""Add RBAC, Subscription, and Organization models

Revision ID: b9adb34cb589
Revises: 002e08600364
Create Date: 2026-08-10 01:39:23.305422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b9adb34cb589'
down_revision = '002e08600364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('plans',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_armada', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('organization_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_units_tenant_id'), 'organization_units', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_role_name')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'past_due', 'canceled', 'unpaid', name='subscription_status_enum'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_index('idx_app_settings_tenant', table_name='app_settings')
    op.drop_index('uq_app_settings_tenant', table_name='app_settings')
    op.create_index(op.f('ix_app_settings_tenant_id'), 'app_settings', ['tenant_id'], unique=False)
    op.drop_index('idx_armada_jenis', table_name='armada')
    op.drop_index('idx_armada_lokasi', table_name='armada')
    op.drop_index('idx_armada_tenant', table_name='armada')
    op.drop_index('uq_armada_kode_tenant', table_name='armada', postgresql_where='(is_deleted = false)')
    op.drop_index('uq_armada_no_lambung_tenant', table_name='armada', postgresql_where='((is_deleted = false) AND (no_lambung IS NOT NULL))')
    op.drop_index('uq_armada_no_polisi_tenant', table_name='armada', postgresql_where='((is_deleted = false) AND (no_polisi IS NOT NULL))')
    op.drop_index('uq_armada_qr_tenant', table_name='armada', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_armada_id'), 'armada', ['id'], unique=False)
    op.create_index(op.f('ix_armada_kode_armada'), 'armada', ['kode_armada'], unique=False)
    op.create_index(op.f('ix_armada_no_lambung'), 'armada', ['no_lambung'], unique=False)
    op.create_index(op.f('ix_armada_no_polisi'), 'armada', ['no_polisi'], unique=False)
    op.create_index(op.f('ix_armada_qr_code_value'), 'armada', ['qr_code_value'], unique=False)
    op.create_index(op.f('ix_armada_tenant_id'), 'armada', ['tenant_id'], unique=False)
    op.drop_index('idx_armada_file_armada', table_name='armada_file')
    op.drop_index('idx_armada_file_tenant', table_name='armada_file')
    op.create_index(op.f('ix_armada_file_armada_id'), 'armada_file', ['armada_id'], unique=False)
    op.create_index(op.f('ix_armada_file_id'), 'armada_file', ['id'], unique=False)
    op.create_index(op.f('ix_armada_file_tenant_id'), 'armada_file', ['tenant_id'], unique=False)
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_user', table_name='audit_log')
    op.drop_index('idx_audit_log_waktu', table_name='audit_log')
    op.drop_index('idx_audit_tenant', table_name='audit_log')
    op.create_index(op.f('ix_audit_log_entitas'), 'audit_log', ['entitas'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_waktu'), 'audit_log', ['waktu'], unique=False)
    op.drop_index('idx_histori_lok_tenant', table_name='histori_lokasi')
    op.drop_index('idx_histori_lokasi_armada', table_name='histori_lokasi')
    op.create_index(op.f('ix_histori_lokasi_armada_id'), 'histori_lokasi', ['armada_id'], unique=False)
    op.create_index(op.f('ix_histori_lokasi_id'), 'histori_lokasi', ['id'], unique=False)
    op.create_index(op.f('ix_histori_lokasi_tenant_id'), 'histori_lokasi', ['tenant_id'], unique=False)
    op.drop_index('idx_histori_status_armada', table_name='histori_status')
    op.drop_index('idx_histori_status_pending', table_name='histori_status', postgresql_where="(approval_status = 'pending'::approval_status_enum)")
    op.drop_index('idx_histori_sts_tenant', table_name='histori_status')
    op.create_index(op.f('ix_histori_status_armada_id'), 'histori_status', ['armada_id'], unique=False)
    op.create_index(op.f('ix_histori_status_id'), 'histori_status', ['id'], unique=False)
    op.create_index(op.f('ix_histori_status_tenant_id'), 'histori_status', ['tenant_id'], unique=False)
    op.drop_index('idx_jadwal_servis_armada', table_name='jadwal_servis')
    op.drop_index('idx_jadwal_servis_due', table_name='jadwal_servis')
    op.drop_index('idx_jadwal_tenant', table_name='jadwal_servis')
    op.create_index(op.f('ix_jadwal_servis_armada_id'), 'jadwal_servis', ['armada_id'], unique=False)
    op.create_index(op.f('ix_jadwal_servis_id'), 'jadwal_servis', ['id'], unique=False)
    op.create_index(op.f('ix_jadwal_servis_tenant_id'), 'jadwal_servis', ['tenant_id'], unique=False)
    op.drop_index('idx_jenis_kend_tenant', table_name='jenis_kendaraan')
    op.drop_index('uq_jenis_kendaraan_nama_tenant', table_name='jenis_kendaraan', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_jenis_kendaraan_id'), 'jenis_kendaraan', ['id'], unique=False)
    op.create_index(op.f('ix_jenis_kendaraan_tenant_id'), 'jenis_kendaraan', ['tenant_id'], unique=False)
    op.drop_index('idx_licenses_tenant', table_name='licenses')
    op.drop_constraint('licenses_license_id_key', 'licenses', type_='unique')
    op.drop_constraint('licenses_license_key_key', 'licenses', type_='unique')
    op.create_index(op.f('ix_licenses_tenant_id'), 'licenses', ['tenant_id'], unique=False)
    op.drop_index('idx_lokasi_tenant', table_name='lokasi')
    op.drop_index('uq_lokasi_nama_tenant', table_name='lokasi', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_lokasi_id'), 'lokasi', ['id'], unique=False)
    op.create_index(op.f('ix_lokasi_tenant_id'), 'lokasi', ['tenant_id'], unique=False)
    op.drop_index('idx_notifikasi_tenant', table_name='notifikasi')
    op.drop_index('idx_notifikasi_user_unread', table_name='notifikasi')
    op.create_index(op.f('ix_notifikasi_id'), 'notifikasi', ['id'], unique=False)
    op.create_index(op.f('ix_notifikasi_tenant_id'), 'notifikasi', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifikasi_user_id'), 'notifikasi', ['user_id'], unique=False)
    op.drop_index('idx_pemeliharaan_armada', table_name='pemeliharaan', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_pemeliharaan_status', table_name='pemeliharaan', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_pemeliharaan_tenant', table_name='pemeliharaan')
    op.create_index(op.f('ix_pemeliharaan_armada_id'), 'pemeliharaan', ['armada_id'], unique=False)
    op.create_index(op.f('ix_pemeliharaan_id'), 'pemeliharaan', ['id'], unique=False)
    op.create_index(op.f('ix_pemeliharaan_tenant_id'), 'pemeliharaan', ['tenant_id'], unique=False)
    op.drop_index('idx_sparepart_pemeliharaan', table_name='sparepart', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_sparepart_tenant', table_name='sparepart')
    op.create_index(op.f('ix_sparepart_id'), 'sparepart', ['id'], unique=False)
    op.create_index(op.f('ix_sparepart_pemeliharaan_id'), 'sparepart', ['pemeliharaan_id'], unique=False)
    op.create_index(op.f('ix_sparepart_tenant_id'), 'sparepart', ['tenant_id'], unique=False)
    op.drop_index('idx_tenant_settings_tenant', table_name='tenant_settings')
    op.drop_index('uq_tenant_settings_tenant', table_name='tenant_settings')
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_index('uq_tenants_slug', table_name='tenants')
    op.create_unique_constraint(None, 'tenants', ['slug'])
    op.drop_index('idx_users_tenant', table_name='users')
    op.drop_index('uq_users_email_tenant', table_name='users', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('administrator', 'pimpinan', 'kabid', 'operator', 'teknisi', name='user_role'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('uq_users_email_tenant', 'users', ['tenant_id', 'email'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.drop_constraint(None, 'tenants', type_='unique')
    op.create_index('uq_tenants_slug', 'tenants', ['slug'], unique=True)
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.create_index('uq_tenant_settings_tenant', 'tenant_settings', ['tenant_id'], unique=True)
    op.create_index('idx_tenant_settings_tenant', 'tenant_settings', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_sparepart_tenant_id'), table_name='sparepart')
    op.drop_index(op.f('ix_sparepart_pemeliharaan_id'), table_name='sparepart')
    op.drop_index(op.f('ix_sparepart_id'), table_name='sparepart')
    op.create_index('idx_sparepart_tenant', 'sparepart', ['tenant_id'], unique=False)
    op.create_index('idx_sparepart_pemeliharaan', 'sparepart', ['pemeliharaan_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_pemeliharaan_tenant_id'), table_name='pemeliharaan')
    op.drop_index(op.f('ix_pemeliharaan_id'), table_name='pemeliharaan')
    op.drop_index(op.f('ix_pemeliharaan_armada_id'), table_name='pemeliharaan')
    op.create_index('idx_pemeliharaan_tenant', 'pemeliharaan', ['tenant_id'], unique=False)
    op.create_index('idx_pemeliharaan_status', 'pemeliharaan', ['status'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('idx_pemeliharaan_armada', 'pemeliharaan', ['armada_id', 'tanggal'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_notifikasi_user_id'), table_name='notifikasi')
    op.drop_index(op.f('ix_notifikasi_tenant_id'), table_name='notifikasi')
    op.drop_index(op.f('ix_notifikasi_id'), table_name='notifikasi')
    op.create_index('idx_notifikasi_user_unread', 'notifikasi', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notifikasi_tenant', 'notifikasi', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_lokasi_tenant_id'), table_name='lokasi')
    op.drop_index(op.f('ix_lokasi_id'), table_name='lokasi')
    op.create_index('uq_lokasi_nama_tenant', 'lokasi', ['tenant_id', 'nama'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index('idx_lokasi_tenant', 'lokasi', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_licenses_tenant_id'), table_name='licenses')
    op.create_unique_constraint('licenses_license_key_key', 'licenses', ['license_key'])
    op.create_unique_constraint('licenses_license_id_key', 'licenses', ['license_id'])
    op.create_index('idx_licenses_tenant', 'licenses', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_jenis_kendaraan_tenant_id'), table_name='jenis_kendaraan')
    op.drop_index(op.f('ix_jenis_kendaraan_id'), table_name='jenis_kendaraan')
    op.create_index('uq_jenis_kendaraan_nama_tenant', 'jenis_kendaraan', ['tenant_id', 'nama'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index('idx_jenis_kend_tenant', 'jenis_kendaraan', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_jadwal_servis_tenant_id'), table_name='jadwal_servis')
    op.drop_index(op.f('ix_jadwal_servis_id'), table_name='jadwal_servis')
    op.drop_index(op.f('ix_jadwal_servis_armada_id'), table_name='jadwal_servis')
    op.create_index('idx_jadwal_tenant', 'jadwal_servis', ['tenant_id'], unique=False)
    op.create_index('idx_jadwal_servis_due', 'jadwal_servis', ['tanggal_jatuh_tempo', 'status'], unique=False)
    op.create_index('idx_jadwal_servis_armada', 'jadwal_servis', ['armada_id'], unique=False)
    op.drop_index(op.f('ix_histori_status_tenant_id'), table_name='histori_status')
    op.drop_index(op.f('ix_histori_status_id'), table_name='histori_status')
    op.drop_index(op.f('ix_histori_status_armada_id'), table_name='histori_status')
    op.create_index('idx_histori_sts_tenant', 'histori_status', ['tenant_id'], unique=False)
    op.create_index('idx_histori_status_pending', 'histori_status', ['approval_status'], unique=False, postgresql_where="(approval_status = 'pending'::approval_status_enum)")
    op.create_index('idx_histori_status_armada', 'histori_status', ['armada_id', 'tanggal'], unique=False)
    op.drop_index(op.f('ix_histori_lokasi_tenant_id'), table_name='histori_lokasi')
    op.drop_index(op.f('ix_histori_lokasi_id'), table_name='histori_lokasi')
    op.drop_index(op.f('ix_histori_lokasi_armada_id'), table_name='histori_lokasi')
    op.create_index('idx_histori_lokasi_armada', 'histori_lokasi', ['armada_id', 'tanggal_pindah'], unique=False)
    op.create_index('idx_histori_lok_tenant', 'histori_lokasi', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_audit_log_waktu'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entitas'), table_name='audit_log')
    op.create_index('idx_audit_tenant', 'audit_log', ['tenant_id'], unique=False)
    op.create_index('idx_audit_log_waktu', 'audit_log', ['waktu'], unique=False)
    op.create_index('idx_audit_log_user', 'audit_log', ['user_id'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_log', ['entitas', 'entitas_id'], unique=False)
    op.drop_index(op.f('ix_armada_file_tenant_id'), table_name='armada_file')
    op.drop_index(op.f('ix_armada_file_id'), table_name='armada_file')
    op.drop_index(op.f('ix_armada_file_armada_id'), table_name='armada_file')
    op.create_index('idx_armada_file_tenant', 'armada_file', ['tenant_id'], unique=False)
    op.create_index('idx_armada_file_armada', 'armada_file', ['armada_id'], unique=False)
    op.drop_index(op.f('ix_armada_tenant_id'), table_name='armada')
    op.drop_index(op.f('ix_armada_qr_code_value'), table_name='armada')
    op.drop_index(op.f('ix_armada_no_polisi'), table_name='armada')
    op.drop_index(op.f('ix_armada_no_lambung'), table_name='armada')
    op.drop_index(op.f('ix_armada_kode_armada'), table_name='armada')
    op.drop_index(op.f('ix_armada_id'), table_name='armada')
    op.create_index('uq_armada_qr_tenant', 'armada', ['tenant_id', 'qr_code_value'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index('uq_armada_no_polisi_tenant', 'armada', ['tenant_id', 'no_polisi'], unique=True, postgresql_where='((is_deleted = false) AND (no_polisi IS NOT NULL))')
    op.create_index('uq_armada_no_lambung_tenant', 'armada', ['tenant_id', 'no_lambung'], unique=True, postgresql_where='((is_deleted = false) AND (no_lambung IS NOT NULL))')
    op.create_index('uq_armada_kode_tenant', 'armada', ['tenant_id', 'kode_armada'], unique=True, postgresql_where='(is_deleted = false)')
    op.create_index('idx_armada_tenant', 'armada', ['tenant_id'], unique=False)
    op.create_index('idx_armada_lokasi', 'armada', ['lokasi_saat_ini_id'], unique=False)
    op.create_index('idx_armada_jenis', 'armada', ['jenis_kendaraan_id'], unique=False)
    op.drop_index(op.f('ix_app_settings_tenant_id'), table_name='app_settings')
    op.create_index('uq_app_settings_tenant', 'app_settings', ['tenant_id'], unique=True)
    op.create_index('idx_app_settings_tenant', 'app_settings', ['tenant_id'], unique=False)
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organization_units_tenant_id'), table_name='organization_units')
    op.drop_table('organization_units')
    op.drop_table('plans')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
