"""Add operator_lapangan table

Revision ID: be14c0846d76
Revises: 27fb79c5cd16
Create Date: 2026-08-27 12:12:17.815167

"""
from alembic import op
import sqlalchemy as sa


revision = 'be14c0846d76'
down_revision = '27fb79c5cd16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_lapangan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nip_nik', sa.String(length=50), nullable=False),
    sa.Column('foto_url', sa.String(length=2048), nullable=True),
    sa.Column('sim_file_url', sa.String(length=2048), nullable=True),
    sa.Column('sim_expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_lapangan_id'), 'operator_lapangan', ['id'], unique=False)
    op.create_index(op.f('ix_operator_lapangan_nip_nik'), 'operator_lapangan', ['nip_nik'], unique=True)
    op.create_index(op.f('ix_operator_lapangan_tenant_id'), 'operator_lapangan', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_operator_lapangan_user_id'), 'operator_lapangan', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_lapangan_user_id'), table_name='operator_lapangan')
    op.drop_index(op.f('ix_operator_lapangan_tenant_id'), table_name='operator_lapangan')
    op.drop_index(op.f('ix_operator_lapangan_nip_nik'), table_name='operator_lapangan')
    op.drop_index(op.f('ix_operator_lapangan_id'), table_name='operator_lapangan')
    op.drop_table('operator_lapangan')
    # ### end Alembic commands ###
