"""rename bahari to relawan

Revision ID: c86befb24e5d
Revises: 37b634d90af8
Create Date: 2026-08-13 22:23:26.543730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c86befb24e5d'
down_revision = '37b634d90af8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insiden_relawan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('lokasi', sa.String(), nullable=False),
    sa.Column('skala', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('jumlah_korban', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insiden_relawan_tenant_id'), 'insiden_relawan', ['tenant_id'], unique=False)
    op.create_table('komunitas_relawan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('lokasi', sa.String(), nullable=False),
    sa.Column('jumlah_anggota', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('kontak_utama', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_komunitas_relawan_tenant_id'), 'komunitas_relawan', ['tenant_id'], unique=False)
    op.create_table('pelatihan_relawan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kapasitas', sa.Integer(), nullable=False),
    sa.Column('peserta_terdaftar', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lokasi', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pelatihan_relawan_tenant_id'), 'pelatihan_relawan', ['tenant_id'], unique=False)
    op.create_table('aset_relawan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipe', sa.Enum('fire_boat', 'fire_pump', 'posko', 'pulau', name='tipeasetrelawan'), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('kapasitas', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ready', 'maintenance', 'deployed', name='statusasetrelawan'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_insiden_bahari_tenant_id', table_name='insiden_bahari')
    op.drop_table('insiden_bahari')
    op.drop_table('aset_bahari')
    op.drop_index('ix_komunitas_bahari_tenant_id', table_name='komunitas_bahari')
    op.drop_table('komunitas_bahari')
    op.drop_index('ix_pelatihan_bahari_tenant_id', table_name='pelatihan_bahari')
    op.drop_table('pelatihan_bahari')
    op.add_column('stations', sa.Column('is_relawan_post', sa.Boolean(), nullable=True))
    op.drop_column('stations', 'is_bahari_post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('is_bahari_post', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('stations', 'is_relawan_post')
    op.create_table('pelatihan_bahari',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tanggal', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('kapasitas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peserta_terdaftar', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lokasi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pelatihan_bahari_pkey')
    )
    op.create_index('ix_pelatihan_bahari_tenant_id', 'pelatihan_bahari', ['tenant_id'], unique=False)
    op.create_table('komunitas_bahari',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lokasi', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jumlah_anggota', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kontak_utama', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nomor_telepon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='komunitas_bahari_pkey')
    )
    op.create_index('ix_komunitas_bahari_tenant_id', 'komunitas_bahari', ['tenant_id'], unique=False)
    op.create_table('aset_bahari',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipe', postgresql.ENUM('fire_boat', 'fire_pump', 'posko', 'pulau', name='tipeasetbahari'), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('kapasitas', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ready', 'maintenance', 'deployed', name='statusasetbahari'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='aset_bahari_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='aset_bahari_pkey')
    )
    op.create_table('insiden_bahari',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('judul', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tanggal', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('lokasi', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('skala', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('jumlah_korban', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='insiden_bahari_pkey')
    )
    op.create_index('ix_insiden_bahari_tenant_id', 'insiden_bahari', ['tenant_id'], unique=False)
    op.drop_table('aset_relawan')
    op.drop_index(op.f('ix_pelatihan_relawan_tenant_id'), table_name='pelatihan_relawan')
    op.drop_table('pelatihan_relawan')
    op.drop_index(op.f('ix_komunitas_relawan_tenant_id'), table_name='komunitas_relawan')
    op.drop_table('komunitas_relawan')
    op.drop_index(op.f('ix_insiden_relawan_tenant_id'), table_name='insiden_relawan')
    op.drop_table('insiden_relawan')
    # ### end Alembic commands ###
