"""Add insiden_regu table

Revision ID: d9618a7a842e
Revises: a7d77b916c14
Create Date: 2026-08-19 07:08:12.476160

"""
from alembic import op
import sqlalchemy as sa


revision = 'd9618a7a842e'
down_revision = 'a7d77b916c14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insiden_regu',
    sa.Column('insiden_id', sa.UUID(), nullable=False),
    sa.Column('regu_id', sa.BigInteger(), nullable=False),
    sa.Column('waktu_dispatch', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['insiden_id'], ['insiden.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regu_id'], ['regu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insiden_id', 'regu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insiden_regu')
    # ### end Alembic commands ###
