"""add relawan details

Revision ID: e0c1a268a7f0
Revises: 88aab93ffc53
Create Date: 2026-08-14 13:50:41.694991

"""
from alembic import op
import sqlalchemy as sa


revision = 'e0c1a268a7f0'
down_revision = '88aab93ffc53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relawan', sa.Column('nik', sa.String(length=50), nullable=True))
    op.add_column('relawan', sa.Column('no_telepon', sa.String(length=50), nullable=True))
    op.add_column('relawan', sa.Column('alamat', sa.String(length=500), nullable=True))
    op.add_column('relawan', sa.Column('provinsi', sa.String(length=100), nullable=True))
    op.add_column('relawan', sa.Column('kota', sa.String(length=100), nullable=True))
    op.add_column('relawan', sa.Column('kecamatan', sa.String(length=100), nullable=True))
    op.add_column('relawan', sa.Column('kelurahan', sa.String(length=100), nullable=True))
    op.add_column('relawan', sa.Column('pekerjaan', sa.String(length=100), nullable=True))
    op.add_column('relawan', sa.Column('pendidikan', sa.String(length=100), nullable=True))
    op.add_column('relawan', sa.Column('golongan_darah', sa.String(length=5), nullable=True))
    op.add_column('relawan', sa.Column('foto_ktp', sa.String(), nullable=True))
    op.add_column('relawan', sa.Column('foto_diri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relawan', 'foto_diri')
    op.drop_column('relawan', 'foto_ktp')
    op.drop_column('relawan', 'golongan_darah')
    op.drop_column('relawan', 'pendidikan')
    op.drop_column('relawan', 'pekerjaan')
    op.drop_column('relawan', 'kelurahan')
    op.drop_column('relawan', 'kecamatan')
    op.drop_column('relawan', 'kota')
    op.drop_column('relawan', 'provinsi')
    op.drop_column('relawan', 'alamat')
    op.drop_column('relawan', 'no_telepon')
    op.drop_column('relawan', 'nik')
    # ### end Alembic commands ###
