// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT9h5Zs-wcY4jJAYnpg0bobqRhK06tX0c',
    appId: '1:880413210421:web:3251456a55dae45f4c7e7c',
    messagingSenderId: '880413210421',
    projectId: 'pyrofar-app',
    authDomain: 'pyrofar-app.firebaseapp.com',
    storageBucket: 'pyrofar-app.firebasestorage.app',
    measurementId: 'G-SVT6SPZ0LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzWAFtWNs-vVn6h7_YshcKwfkzGvvJH4s',
    appId: '1:880413210421:android:6ca96e1b653c1be44c7e7c',
    messagingSenderId: '880413210421',
    projectId: 'pyrofar-app',
    storageBucket: 'pyrofar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLWspeNct7zpBxdzUO85eoesgTIh22Lgk',
    appId: '1:880413210421:ios:4a7202714630188b4c7e7c',
    messagingSenderId: '880413210421',
    projectId: 'pyrofar-app',
    storageBucket: 'pyrofar-app.firebasestorage.app',
    iosBundleId: 'id.go.makassar.damkar.simArmadaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLWspeNct7zpBxdzUO85eoesgTIh22Lgk',
    appId: '1:880413210421:ios:4a7202714630188b4c7e7c',
    messagingSenderId: '880413210421',
    projectId: 'pyrofar-app',
    storageBucket: 'pyrofar-app.firebasestorage.app',
    iosBundleId: 'id.go.makassar.damkar.simArmadaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT9h5Zs-wcY4jJAYnpg0bobqRhK06tX0c',
    appId: '1:880413210421:web:4b1430b34e546fda4c7e7c',
    messagingSenderId: '880413210421',
    projectId: 'pyrofar-app',
    authDomain: 'pyrofar-app.firebaseapp.com',
    storageBucket: 'pyrofar-app.firebasestorage.app',
    measurementId: 'G-F86X67GS68',
  );
}
